modLoader="javafml"
loaderVersion = "[42,)"
license="EPL-1.0"
issueTrackerURL="https://github.com/iGoodie/TwitchSpawn/issues"

[[mods]]
modId="twitchspawn"
version = "${version}"
displayName="TwitchSpawn"
authors="iGoodie, BONNe1704"
logoFile="pack.png"
description='''
    TwitchSpawn listens for live events related to your Twitch channel using various Socket APIs.
    Then it handles those events with the rules handcrafted by you!
'''

[[dependencies.twitchspawn]]
    modId = "forge"
    mandatory = true
    versionRange = "[42,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.twitchspawn]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.twitchspawn]]
    modId = "architectury"
    mandatory = true
    versionRange = "[6.3.56,)"
    ordering = "AFTER"
    side = "BOTH"
