# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.10.0-unofficial
maven_group = net.programmer.igoodie.twitchspawn
archives_name = twitchspawn
enabled_platforms = fabric,forge

# Minecraft properties
minecraft_version = 1.19.1

# Dependencies
architectury_api_version = 6.3.56
fabric_loader_version = 0.16.14
fabric_api_version = 0.58.5+1.19.1
forge_version = 1.19.1-42.0.9

night_config_version = 3.6.4
okhttp_version = 3.8.1
socket_version = 1.0.2
